language: objective-c

before_script:
- gem install luffa --no-document --no-document --env-shebang --no-prerelease
- gem install xcpretty --no-document --no-document --env-shebang --no-prerelease
- luffa authorize
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc

script:
- bundle install
- bundle exec bin/ci/test-cloud.rb
- bundle exec bin/ci/travis/run.rb

notifications:
  email:
    recipients:
    - josmoo@microsoft.com
    on_success: change
    on_failure: always
  slack:
    rooms:
      secure: CrmEHmKBuCFwuImLwK1Xn45XFzVb9iNxMfryA7YQsc1+Jc7m5/ot8eXUSxY8sEFN4hRfSRA4Dm27vdw9y0LbPfq76hSEFHVflebGhWK7yrLWcUGePZDibHHrU5Uqa6zmhwmQQaZFPCL4ZZ9yFJYf+DT5Q2XWTKD1TvEzyIvgt0I=

