source "https://rubygems.org"

gem "calabash-cucumber", :github => "calabash/calabash-ios", :branch => "develop"
gem "cucumber", "2.99.0"
gem "run_loop", :github => "calabash/run_loop", :branch => "develop"
gem "json", "2.3.0"
gem "briar", "~> 2.0"
gem "luffa", "2.1.0"

# Keep these sync'd with bin/make/ipa-cal.sh
gem "rspec", "~> 3.0"
gem "xamarin-test-cloud", "~> 2.1"

gem "xcpretty"
gem "pry"
gem "pry-nav"
